version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3000' # Map container port 3000 to host port 3001
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: pnpm dev
